### ISSUE TITLE
Key.Activate returns "Could not find the key" error or Win32Exception

### ISSUE THREAD

**Issue by RealBrandonChen** [Cryptolens/cryptolens-dotnet#73]
### In Unity, I got "Could not find the key" error when running `machineCode = "foo"`  and 
>Win32Exception: ApplicationName='cmd.exe', CommandLine='/C wmic csproduct get uuid', CurrentDirectory='', Native error= no files in the system.
System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) (at <aa976c2104104b7ca9e1785715722c9d>:0)
System.Diagnostics.Process.Start () (at <aa976c2104104b7ca9e1785715722c9d>:0)
(wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()

### The code as belows:
```C#
var RSAPubKey = "<RSAKeyValue><Modulus>***</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>";
var auth = "WyIyMjQ5MDM0IiwiM3hoV2ZpWENWWHA4LzNsTnFOc1BJaDBlblArN1RVREE2bzJWUFlNRCJd";
Helpers.WindowsOnly = true;
var machineCode = Helpers.GetMachineCodePI();
//var machineCode = "foo";
var result = Key.Activate(token: auth, productId: 11596, key: "EPLVQ-LDNEM-DDUPD-TLBQY", machineCode: machineCode);
```

## PS: Even if the error comes with "Could not find the key", the Log API Logs still detects the key verification error:
>
<html>
<body>

Status | Error
-- | --
ID | 83915679
Time (UTC) | 2021-07-06 08:29:00
IP | 116.**.***.0
Product Id | 11596
Key | EPLVQ-LDNEM-DDUPD-TLBQY
Machine Code | foo
Friendly Name |  
Operation | The activation was not successful (no machine locking was enabled)
State | 2020
Anomaly | No

</body>
</html>

**Comment by artemlos** [comment]
@RealBrandonChen Hi!

Thanks for your question.

I checked on our end and it appears that the first issue (that returned `Could not find the key`) is because of the access token. The one that was used has Key Lock set to a non-zero value. To fix this, could you please re-create the access token so that this value is set to zero (or empty), i.e. as follows:

![image](https://user-images.githubusercontent.com/6392760/124598061-7ff83180-de64-11eb-8983-df8f5fe7d5f5.png)

Regarding the second error, could you please check if the following method works better? `Helpers.GetMachineCode()`?

**Comment by RealBrandonChen** [comment]
@artemlos Thanks for your reply! It perfectly solve the first question and the Key Verification now turns to Sucess with Key Lock set to non-zero! But I still can not get the machine code and the Log API Logs had no response if I was running `Helpers.GetMachineCode()` or `Helpers.GetMachineCodePI()`.
