### ISSUE TITLE
NTP time servers

### ISSUE THREAD

**Issue by keifgwinn** [Cryptolens/cryptolens-dotnet#78]
Currently it's set to use time.windows.com based on the example code, but time.windows.com has been unreliable recently, with many failed checks. Could you move to 'pool.ntp.org' and also add in some retries

**Comment by artemlos** [comment]
@keifgwinn An update is released which uses the new servers. For now, we don't have a retry built in, however, my suggestion would be to encapsulate this into a try-catch and call it again should it fail. I would also suggest using SKGL.SKM.TimeCheck right away instead of the helper methods, so that you can allow the application to run for a limited period of time until it succeeds, for example to check in a background process.

The reason a re-try logic was not added is to avoid a situation where the check freezes for some time and the user does not have access to the software. It could be a situation that no internet is available at the time, not related to time tampering.

If the call to Key.Activate is made and automatic blocking of expired licenses is enabled (https://help.cryptolens.io/faq/index#blocking-expired-licenses), there is no need to perform the time check since our server will automatically block all expired licenses (that are marked as time-limited)
